name: pull-request
on:
  pull_request:
    branches: [ dev, master ]
    types: [ opened, synchronize, reopened ]

permissions:
  actions: read
  packages: write
  contents: write
  id-token: write
  checks: write
  security-events: write

jobs:
  sanity:
    uses: ./.github/workflows/reusable-sanity.yml

  test:
    uses: ./.github/workflows/reusable-test.yml
    needs: [ sanity ]
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
