name: code-ql
on:
  workflow_dispatch:
  workflow_call:
env:
  DOTNET_VERSION: "9.0.x"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: "csharp"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: https://nuget.pkg.github.com/piotrkantorowicz/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore src/Diksy.WebApi/Diksy.WebApi.csproj

      - name: Build
        run: dotnet build src/Diksy.WebApi/Diksy.WebApi.csproj --configuration Release --no-restore

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
